package com.edgestackers.opticon.common.datamodel;


public record PacmanRunFlucsUpdate(int tab,
                                   String runnerName,
                                   String marketId,
                                   String selectionId,
                                   String runnerTotalMatched,
                                   String marketTotalMatched,
                                   double backMarketPct,
                                   String layMarketPct,
                                   double tradedWap,
                                   double atb1p,
                                   double atb2p,
                                   double atb3p,
                                   double atb1s,
                                   double atb2s,
                                   double atb3s,
                                   double atl1p,
                                   double atl2p,
                                   double atl3p,
                                   double atl1s,
                                   double atl2s,
                                   double atl3s,
                                   double tradedTwap30s,
                                   double tradedTwap60s,
                                   double tradedTwap120s,
                                   double tradedTwap240s,
                                   double tradedTwap300s,
                                   double tradedTwap600s,
                                   double tradedTwap900s,
                                   double tradedVolume30s,
                                   double tradedVolume60s,
                                   double tradedVolume120s,
                                   double tradedVolume240s,
                                   double tradedVolume300s,
                                   double tradedVolume600s,
                                   double tradedVolume900s) {
}
